accounts/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
#    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth import views as auth_views
from kintai.views import top
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar  #本番時消す


# adminサイトの表示カスタマイズ
admin.site.site_title = 'e-ize管理画面'
admin.site.site_header = 'e-ize管理画面'
admin.site.index_title = 'メニュー'


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', top.SampleTemplateView.as_view(), name='top'),
    path('kintai/master/', include('kintai.urls.master_urls')),
    path('kintai/roster/', include('kintai.urls.roster_urls')),
    path('kintai/salaried/', include('kintai.urls.salaried_urls')),
    path('kintai/management/', include('kintai.urls.management_urls')),
    path('login', RedirectView.as_view(url='/accounts/login/'), name='login'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]
# 印影画像格納先を指定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from kintai.models import User
from django.contrib.auth.forms import PasswordChangeForm


class LoginForm(AuthenticationForm):
    error_messages = {
        'invalid_login': "メールアドレス、またはパスワードが違います。",
        'inactive': "このアカウントは無効です",
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'メールアドレス'

        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['placeholder'] = 'パスワード'

# adminでユーザー登録行うから多分使わない
class RegisterForm(UserCreationForm):
    # 入力を必須にするため、required=Trueで上書き
    email = forms.EmailField(required=True)

    class Meta:
        model = User

        fields = (
            "email", "password1", "password2",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレス'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'パスワード'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'パスワード（確認）'

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.conf import settings
from .forms import LoginForm, RegisterForm
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import views
from axes.utils import reset
from django.shortcuts import resolve_url
from axes.models import AccessAttempt

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

import logging
logging.getLogger(__name__)

class LoginView(views.LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def get_success_url(self):
        count = reset(username=self.request.user.email)
        return resolve_url(settings.LOGIN_REDIRECT_URL)

def reset(username: str = None) -> int:
    """
    ログイン成功時にアクセスログを削除（5回間違えるまでに成功したらリセット）
    """
    attempts = AccessAttempt.objects.all()
    attempts.filter(username=username)

    count = attempts.delete()
    logging.info('AXES: Reset %s access attempts from database.', count)
    return count


# adminでユーザー登録行うから多分使わない
class SignUpView(generic.CreateView):
    form_class = RegisterForm
    success_url = reverse_lazy('accounts/login')
    template_name = 'accounts/signup.html'


# 以下4つはパスワード忘れた時の処理
class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'accounts/mail_template/password_reset/subject.txt'
    email_template_name = 'accounts/mail_template/password_reset/message.txt'
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'accounts/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'accounts/password_reset_complete.html'

accounts/templates/accounts/login.html
{% extends 'account_base.html' %}
{% block content %}

<h5 class="text-center">社内システム ログイン</h5><br>
<a href="{% url 'accounts:password_reset' %}" class="password_reset">パスワード再発行</a>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
        <div>{{form.non_field_errors}}</div>
        {% endif %}
        <p><input type="text" name="username" autofocus class="form-control" placeholder="メールアドレス" required id="id_username"></p>
        <p><input type="password" name="password" class="form-control" placeholder="パスワード" required id="id_password"></p>

        <button type="submit" class="submit css_btn_blue mx-auto d-block">ログイン</button>
    </form>
</section>


{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'account_base.html' %}

{% block content %}
<h5>Logout</h5>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Logout</button>
    </form>
</section>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'account_base.html' %}
{% block content %}

<form action="" method="POST">
    <h5 class="text-center">パスワードリセット</h5><br>
    <p>
        パスワード再設定を完了しました。<br>
        <a href="{% url 'accounts:login' %}">ログイン</a>
    </p>
</form>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'account_base.html' %}
{% block content %}

<h5>パスワードリセット</h5><br>

<form action="" method="POST">
    {{ form.non_field_errors }}

    <div align="center">
    <div class="form-group">
        <input type="password" name="new_password1" required id="id_new_password1" placeholder="新しいパスワード">
    </div>
    <div class="form-group">
        <input type="password" name="new_password2" required id="id_new_password2" placeholder="新しいパスワード(確認用)">
    </div>
    </div>
    {% csrf_token %}
    <button type="submit" class="css_btn_blue mx-auto d-block">送信</button>
</form>

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'account_base.html' %}
{% block content %}

<h5>パスワードリセット（メール送信）</h5><br>
<form action="" method="POST">
    <div align="center">
        <p>パスワードリセットのメールを送信しました。
            <br/>
            リンクからパスワードの再設定を行ってください。
            <br/>
            <br/>
            <br/>
            <a href="{% url 'accounts:login' %}" style="text-align:center">ログイン画面へ戻る</a>
        </p>
    </div>
</form>

{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends 'account_base.html' %}
{% block content %}

<div class="text-center">
<h5>パスワードリセット</h5><br>
<a href="{% url 'accounts:login' %}">ログイン画面へ</a>
<form action="" method="POST">
    {{ form.non_field_errors }}
    <p>メールを受信してパスワードの変更手続きを行います。</p>
    <p>メールアドレスを入力して送信ボタンを押してください。</p>
    {% for field in form %}
    <div class="form-group">
        <input type="email" name="email" maxlength="254" required id="id_email" placeholder="メールアドレス">
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <pre>メールが届かない場合はシステム管理者に連絡してください。</pre>
    <br/>
    <button type="submit" class="css_btn_blue mx-auto d-block">送信</button>
</form>
    </div>

{% endblock %}

    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}

accounts/templates/accounts/signup.html
{% extends 'account_base.html' %}
{% block content %}

<h1>Sign up</h1>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Sign up</button>
    </form>
</section>
{% endblock %}